### ISSUE TITLE
All epoptes users have the same rights

### ISSUE THREAD

**Issue by ftsamis** [epoptes/epoptes#10]
Currently all epoptes users are permitted to execute whatever command they wish on the clients, open a terminal and even a root terminal.

Epoptes (daemon) should have a permissions system with which you could set roles and allow each user to perform certain actions only.

Launchpad Details: [#LP1203299](https://bugs.launchpad.net/bugs/1203299) Fotis Tsamis - 2013-07-20 13:12:46 +0000

**Comment by alkisg** [comment]
The main separation is "run system commands or session commands".
This can already be done by adding a line in /etc/default/epoptes-client:

```shell
test $(id -u) -eq 0 && SERVER=server1 || SERVER=server2
```

Then user that have access to server1 can control everything, while people that have access to server2 can control only user sessions.
Of course it's not the same as a full permissions system, but so far it appears to be enough.
