### ISSUE TITLE
Use lowercase in MAC addresses

### ISSUE THREAD

**Issue by fottsia** [epoptes/epoptes#102]
The new LTSP is case sensitive and needs lower case in MAC addresses, so the typical way of copying from Epoptes properties dialogs to ltsp.conf doesn't work anymore.

Additionally, pxelinux uses lowercase in 01-mac-address letters, the kernel uses lowercase etc.

**Comment by alkisg** [comment]
Fix committed in https://github.com/epoptes/epoptes/commit/c7fb2e41855117eab2072de85f8b87d1e9826a60.
