### ISSUE TITLE
Epoptes client doesn't start in 16.04

### ISSUE THREAD

**Issue by fottsia** [epoptes/epoptes#107]
While testing the new LTSP, I saw that the epoptes-client service doesn't automatically start in Ubuntu 16.04, while it starts properly in Ubuntu 18.04.

Version: 1.0.1-2+t201909120629~ubuntu16.04.1

**Comment by alkisg** [comment]
Thanks, fix committed in https://github.com/epoptes/epoptes/commit/eb99a2b84330b869be4e305d753e8fd86a437f16.
