### ISSUE TITLE
Missing dependencies in epoptes-client

### ISSUE THREAD

**Issue by tquest1** [epoptes/epoptes#108]
I have installed this on a Raspbian Desktop (Buster) to use with Raspbian's builtin PiServer. I also installed the client succesfully by chroot in the shared OS for the Network booted Pis.

I can successfully use monitoring & broadcasting from the Piserver to the clients but cannot send messages or execute commands.

I also do not get screenshots of the clients. 

I have seen that someone previously mentioned that 2 x epoptes services should be running on the client - & they are.

Any ideas?

**Comment by alkisg** [comment]
From a client, open two terminals.
In the first one, run /usr/sbin/epoptes-client
In the second one, run sudo /usr/sbin/epoptes-client

Try to do whatever actions you want, and paste the error messages of the terminals for the actions that fail.

**Comment by tquest1** [comment]
Piserver works with the client Pis booting off of read-only NFS shares on the server. Users then login at any Pi client & their home folder is also an NFS mount on the server. Users DO NOT have sudo rights so I can't run the epoptes-client manually from the terminal as sudo. It is running however this is the result of ps faux | grep epoptes:


`student1@raspberrypi:~ $ ps faux | grep epoptes
root       426  0.0  0.2   5768  4308 ?        Ss   03:31   0:00 socat -T 60 openssl-connect:piserver:789,cafile=/etc/epoptes/server.crt,commonname="",interval=60,forever EXEC:bash -c \"exec -a epoptes-client sh\"
root       481  0.0  0.0   1940  1160 ?        S    03:31   0:00  \_ epoptes-client
student1   986  0.0  0.0   7348   560 pts/1    S+   03:35   0:00          |           \_ grep --color=auto epoptes
student1   798  0.0  0.1   5768  3648 ?        S    03:33   0:00 socat -T 60 openssl-connect:piserver:789,cafile=/etc/epoptes/server.crt,commonname="",interval=60,forever EXEC:bash -c \"exec -a epoptes-client sh\"
student1   834  0.0  0.0   1940  1204 ?        S    03:33   0:00  \_ epoptes-client
student1@raspberrypi:~ $ `



The non-sudo command does run though. This is the results when running it - this repeats constantly:

`/usr/sbin/epoptes-client 
Epoptes-client connecting to piserver:789...   ...done
Traceback (most recent call last):
  File "./thumbshot.py", line 11, in <module>
    import cairo
ModuleNotFoundError: No module named 'cairo'
1 failed thumbshots so far!
Traceback (most recent call last):
  File "./thumbshot.py", line 11, in <module>
`
When sending a message:
`Traceback (most recent call last):
  File "./message.py", line 11, in <module>
    from _common import gettext as _
  File "/usr/share/epoptes-client/_common.py", line 31, in <module>
    gi.require_version('Notify', '0.7')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Notify not available`

**Comment by alkisg** [comment]
It sounds like you're missing some packages. How did you install epoptes, maybe with `dpkg -i` or with `apt install --no-install-recommends`?

Please reinstall it with `apt install --install-recommends` as mentioned in the [installation instructions](https://epoptes.org/installation/).

**Comment by alkisg** [comment]
Hmm, I see that we have python3-gi-cairo declared as a dependency of epoptes, but not of epoptes-client.
We mostly test with LTSP, where both those packages exist. Or in Ubuntu/Debian workstations, where python3-gi-cairo is preinstalled anyway.

So it's possible that you did the installation properly and the python3-gi-cairo dependency is missing in your case. Can you try installing these?

```shell
apt install notification-daemon python3-gi-cairo
```

**Comment by tquest1** [comment]
OK, I had already installed with recommends but I added notification-daemon & python3-gi-cairo and executing programs now works, but screenshots & messaging is the still the same:

`student1@raspberrypi:~ $ /usr/sbin/epoptes-client
Epoptes-client connecting to piserver:789...   ...done
Traceback (most recent call last):
  File "./thumbshot.py", line 13, in <module>
    from _common import gettext as _
  File "/usr/share/epoptes-client/_common.py", line 31, in <module>
    gi.require_version('Notify', '0.7')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Notify not available
1 failed thumbshots so far!
Traceback (most recent call last):
  File "./message.py", line 11, in <module>
    from _common import gettext as _
  File "/usr/share/epoptes-client/_common.py", line 31, in <module>
    gi.require_version('Notify', '0.7')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Notify not available`

**Comment by alkisg** [comment]
Here are some more dependencies, install them one by one until it runs:

gir1.2-notify-0.7 gir1.2-gtk-3.0 librsvg2-common

It seems we need to add some dependencies to epoptes-client :)

**Comment by tquest1** [comment]
It just needed gir1.2-notify-0.7 & then everything worked! Thanks a lot for your help Alkis! So the epoptes client just needs to have those missing dependencies added for it to work on Raspbian PiServer.

The only other problem I see is that the server control app shuts down when disconnecting from any client remote session.

**Comment by alkisg** [comment]
I think that second problem is that your server is missing the notification daemon or that you're running epoptes over ssh -X. In this case, the reason and the solution are analyzed in issue #33.

I will leave this issue open until I properly check and fix all the epoptes-client dependencies.

**Comment by alkisg** [comment]
Thanks, fix committed in 1f3c1b78f0dc697f356c57c3a317c4940334d7db.
Additionally, I demoted some Depends: to Recommends:, so that it can be used for headless / xorgless systems as well.
