### ISSUE TITLE
Should allow configure port range for incoming VNC connections to teachers computer

### ISSUE THREAD

**Issue by ftsamis** [epoptes/epoptes#11]
In current design (any free port selected) connections are blocked by firewall. So It'll be very useful to allow to set port range manually in configuration file (and allow connections to that ports in UFW configuration).

Launchpad Details: [#LP1244975](https://bugs.launchpad.net/bugs/1244975) Roman Bazalevsky - 2013-10-26 14:07:47 +0000

**Comment by ftsamis** [comment]
Thanks for the bug report, there are a few difficulties because epoptes needs many ports depending on how many clients are connected, but we'll try to integrate epoptes with ufw.

https://help.ubuntu.com/12.04/serverguide/firewall.html#ufw-application-integration

Launchpad Details: [#LPC](https://bugs.launchpad.net/epoptes/+bug/1244975/comments/1) Alkis Georgopoulos - 2013-10-29 18:03:04 +0000

**Comment by mikehardy** [comment]
Just a quick note that port 789 is needed for the epoptes-client -> epoptes server connection, and if you open 35000-55000 (huge range, not optimal but does work) then the VNC connections appear to work as well, throughout my lab at least.

Also, the UFW integration link appears broken to me, but this has information for UFW users: https://askubuntu.com/questions/409013/how-do-you-create-an-app-profile-for-ufw

I'm using shorewall, so for me on my server I put this in there:
ACCEPT loc $FW tcp 789
ACCEPT loc $FW tcp 35000:55000

Hope this helps someone!

**Comment by dashohoxha** [comment]
One can also allow connections like this (with UFW):

```bash
ufw allow in on eth0
# or
ufw allow from 192.168.1.0/24
```

**Comment by alkisg** [comment]
Closed by GSoC 2023 Epoptes improvements #204.
Please test if the [proposed PPA build](https://epoptes.org/documentation/ppa/) resolves this issue.
