### ISSUE TITLE
Can't broadcast screen over gdm3

### ISSUE THREAD

**Issue by fottsia** [epoptes/epoptes#111]
On Ubuntu (GNOME) 18.04 and 20.04, if the students haven't logged in, teacher screen broadcasting doesn't work.

If I install lightdm instead of gdm3, it works fine, so it's probably related to gdm3.

**Comment by alkisg** [comment]
I discussed this in #gnome, and one of its developers said:

>  GDM doesn’t do anything graphic in GNOME; its only role is to provide the logic and infrastructure for authenticating a user; the way it works is that a specific user (gdm) spawns a GNOME Shell instance in a “login” mode, with limited capabilities
 So: no other clients can run at that point
I’m sorry, it seems you’re trying to do something we pretty specifically don’t support for a variety of reasons
Using lightdm will prevent you from doing other things, but it seems you’re in a very niche use case
Screen broadcasting can happen during a session, not when the user isn’t logged in/authenticated

This means that **Epoptes cannot support broadcasting over GDM3.
Users that need that functionality may install LightDM instead**:

```shell
apt install lightdm
```

To reproduce this issue for testing without even involving Epoptes, one could log in as root on vt2 and run:

```shell
DISPLAY=:0 XAUTHORITY=/run/user/*/gdm/Xauthority xterm
```
