### ISSUE TITLE
Add documentation for wireguard

### ISSUE THREAD

**Issue by alkisg** [epoptes/epoptes#114]
The wireguard in-kernel VPN will be available in Ubuntu 20.04 Focal and Debian 11 Bullseye.
At the very least, a page should be written in epoptes.org to document how to use wireguard to secure all traffic, to allow a single open port in firewalls, to allow epoptes to work seamlessly behind client NAT etc.

**Comment by dashohoxha** [comment]
This might be related or useful:
https://www.researchgate.net/publication/345485273_Distributed_Computer_Lab

**Comment by alkisg** [comment]
Since wireguard is now integrated to the network-manager menus, it's really a point and click process. A lot of documentation already exists and there's no need for epoptes-specific documentation after all.

Here's another good tutorial, that uses just the minimally required packages:
https://www.xmodulo.com/wireguard-vpn-network-manager-gui.html
