### ISSUE TITLE
Display clients screens in icons does in 2 seconds refresh delay - no continous.

### ISSUE THREAD

**Issue by abixadamj** [epoptes/epoptes#122]
When I start Epoptes, it shows clients as icons. When Client is logging, the screen appears. That is OK.
But when user is doing something on client, in Epoptes I see client's screen refreshing every 2 seconds.
Can I change some config to see clients screens in real time?

**Comment by alkisg** [comment]
There's no user setting for that, you'd need to directly edit the code. It's the following line, 5000 means 5 seconds. After changing it you just need to close and open the Epoptes GUI for the change to take effect.
Take care not to make it too frequent as it will end up taking a lot of client CPU; run `top` on the client to see.

```shell
$ grep 5000 /usr/lib/python3/dist-packages/epoptes/ui/gui.py
                GLib.timeout_add(5000, self.ask_thumbshot, handle)
```

**Comment by alkisg** [comment]
This can now be defined in /etc/default/epoptes, by adding something like the following:

```shell
# Ask for a thumbshot every 60 seconds
THUMBSHOT_MS=60000
```

This feature is currently undocumented, as I haven't tested what happens when someone uses very very low msec values there, such as THUMBSHOT_MS=0.
