### ISSUE TITLE
Epoptes does not exclude the host computer from the detected clients list

### ISSUE THREAD

**Issue by mathphi** [epoptes/epoptes#123]
The Epoptes GUI sometimes does not exclude the host computer from the list, so teachers can lock/reboot/... their own computers.
It seems that the list `self.current_macs` in `gui.py` sometimes contains the mac address of the current computer in uppercase, but this address is later compared to the same in lowercase.
Converting all mac addresses from `self.current_macs` to lowercase fixes the problem.

**Comment by alkisg** [comment]
Hi @mathphi, which epoptes server and client versions are you using?

I think that commit 17fe371609e6ed78ab5a2ea6c07106896fb1f8c9 was supposed to fix this issue,
so I removed the "sed lowercase code" from there, as it didn't cover LTSP_CLIENT_MAC,
and then I forgot to add a call to lower() from python...

Does the following work?

    stdout=subprocess.PIPE).communicate()[0].decode().lower().split()

**Comment by mathphi** [comment]
Hi @alkisg, 

We are using version 20.01-1 (the latest from the PPA).
I'm already using the same fix you suggest: adding `lower()` after `decode()` makes it work fine.

Thank you for your reply and for your great project

**Comment by alkisg** [comment]
Thanks, fix committed in 5863f5e.
I pondered completely removing support for LTSP5 (where this problem is), but I guess it still has a couple of years of support in Debian, so I won't remove it yet.
