### ISSUE TITLE
needs to disable SNI from socat calls

### ISSUE THREAD

**Issue by vagrantc** [epoptes/epoptes#127]
socat 1.7.4 (recently updated in Debian bullseye) defaults to using Server Name Indication (SNI), but this breaks epoptes use of socat:

    $ /usr/sbin/epoptes-client 
    Epoptes-client connecting to server:789...2021/02/01 18:39:47 socat[1483] E Failed to set SNI host ""

I tried passing lts.conf to disable verification, but it still had the same issue:

    [common]
    EPOPTES_CLIENT_VERIFY_CERTIFICATE = False

This patch worked for me, though I'm not sure if other corner-cases are triggered:

    --- /usr/sbin/epoptes-client    2021-01-11 14:47:37.000000000 -0800
    +++ epoptes-client      2021-02-01 18:35:53.216014334 -0800
    @@ -248,6 +248,7 @@
         # support certificates which don't have a commonname set
         if socat -hhh | grep -q openssl-commonname; then
             cert_param="$cert_param,commonname=\"\""
    +       cert_param="$cert_param,no-sni=1"
         fi
     else
         cert_param="verify=0"

**Comment by alkisg** [comment]
Thank you Vagrant, fix committed in a519dac.

I also fixed a few shellcheck warnings. Should we release 21.02-1? If you want to, go ahead, if you want me to, ping!
