### ISSUE TITLE
epoptes: rename master branch to main

### ISSUE THREAD

**Issue by fottsia** [epoptes/epoptes#133]
Please rename the master branch to main, as documented in https://github.com/github/renaming.

**Comment by alkisg** [comment]
I renamed master to main via the web interface. Github advises that local copies should be updated by running:

```shell
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

I'll also update some places of the code that reference "master" in URLS, to main.

**Comment by alkisg** [comment]
I also renamed master to main in the launchpad repository clone that is used for the PPA .deb packages,
and in the respective launchpad recipes.
I didn't update it in the translations, as we're manually uploading the .pot periodically now.
