### ISSUE TITLE
sddm XAUTHORITY not correctly set

### ISSUE THREAD

**Issue by Canx** [epoptes/epoptes#136]
In [get-display](https://github.com/epoptes/epoptes/blob/main/epoptes-client/get-display) file XAUTHORITY variable is not correctly set when using sddm, so I can't connect when computer is still in login screen.

I found an example to extract XAuthority file for sddm [here](https://gist.github.com/garymacindoe/e6adae5da32a0db0e82d8bd2ff9ea8ff#file-redshift-conf-d-L27).

**Comment by alkisg** [comment]
It works for me on Debian Bullseye + KDE Plasma:

```shell
root@bullseye-kde:~# /usr/share/epoptes-client/get-display 
DISPLAY=:0
XAUTHORITY=/var/run/sddm/{49730df8-77ab-4d8b-9dfc-697c0382fff3}
```

Which distribution/version are you using?

**Comment by Canx** [comment]
Hi, I am using Lliurex, an education distribution from Spain, that is currently based on KDE Neon 18.04LTS. 

Did you get that results after login in or from a terminal (Ctrl+Alt+F2) without X login in?

**Comment by alkisg** [comment]
I logout from user,
I go to epoptes on the server and right click > open root terminal,
and I run that command.

What do you get if you run that command from epoptes, before login?

**Comment by Canx** [comment]
Empty XAUTHORITY, I think it goes to plan D (I'm not currently in school to double check). I made a dirty hack a time ago in my clients:

https://gist.github.com/Canx/db2692a29e399ee7e2c97aebd837f4c0#file-get-display-L52

**Comment by alkisg** [comment]
Can you upload the output of `ps faux > /tmp/ps-faux.txt` at that time?

**Comment by Canx** [comment]
Hi Alkis,

I'll post you the output tomorrow when I test it at school.

We are using an old Ubuntu version (0.5.7) [http://lliurex.net/bionic/pool/main/e/epoptes/], but it seems get-display hasn't changed since then.

**Comment by alkisg** [comment]
OK. If you're in Spain, we're in nearby timezones (I'm in Greece), so you may also come to IRC for remote support if you want (https://ltsp.org/advanced/chat-room/).

**Comment by Canx** [comment]
Good morning!

I send the `ps faux` output attached from a client. There you can see how Xorg gets the cookie file from a random file name in /var/run/sddm/:

`/usr/lib/xorg/Xorg -nolisten tcp -auth /var/run/sddm/{a65b1b5a-9376-4add-9e45-0f41e54aa896} -background none -noreset -displayfd 17 -seat seat0 vt1`

When I execute get-display as a root (ssh) I get this:

```
root@lliurex05:/usr/share/epoptes-client# ./get-display 
./get-display: 77: ./get-display: ck-list-sessions: not found
Could not detect or access the active display
DISPLAY=
XAUTHORITY=
```

[ps-faux.txt](https://github.com/epoptes/epoptes/files/6746612/ps-faux.txt)

**Comment by alkisg** [comment]
Good morning, the get-display script has been updated since 0.5.10.
Try copying the most recent one over the old one, it should work with SDDM.

**Comment by Canx** [comment]
You're right! I should have tested latest repo version first... I'll try to convince our distribution developers to update the package.

Thanks! And thank you for developing epoptes, I use it everyday at school and it's great!

**Comment by alkisg** [comment]
You're welcome, closing the issue with "already fixed".
