### ISSUE TITLE
Network benchmark fails on Debian Bullseye

### ISSUE THREAD

**Issue by fottsia** [epoptes/epoptes#137]
Recent versions of iperf2 seem to have some bugs, and network benchmark fails on Debian Bullseye.
Maybe it's time to move to iperf3?

**Comment by alkisg** [comment]
Unfortunately iperf3 doesn't support [multiple clients in parallel](https://github.com/esnet/iperf/issues/140#issuecomment-877829168) so it's not an option.

For iperf2, [upstream recommends 2.1.3](https://sourceforge.net/p/iperf2/discussion/general/thread/ac940a4ed3/), which isn't yet available in Debian.

For now, I'll upload focal's iperf to the [Greek schools Debian PPA](https://launchpad.net/~ts.sch.gr/+archive/ubuntu/debian/+packages), with a bumped version number.

While for the future, we'll need to reimplement the network benchmark functionality in pure python, similar to [this github project](https://github.com/Barthurmun/Iperf-in-Python). Patches most welcome!

**Comment by alkisg** [comment]
Closing this one in favor of #183.
