### ISSUE TITLE
Client should retain its previous state upon reboot

### ISSUE THREAD

**Issue by ftsamis** [epoptes/epoptes#14]
When the clients screen is locked, or the servers screen is broadcasted, the students often press the reset button on their client to unlock their screen.

To avoid that, when a client is rebooted, it should ask the server for its previous state, to continue showing the servers screen, or to continue having its screen locked.

This should be a feature in the next update.

Launchpad Details: [#LP1356978](https://bugs.launchpad.net/bugs/1356978) Ioannis Kyriazis - 2014-08-14 16:36:29 +0000

**Comment by ftsamis** [comment]
Thanks Ioannis, that's a good idea, currently the state is only kept client-side, but keeping some of it server-side too makes sense.

Launchpad Details: [#LPC](https://bugs.launchpad.net/epoptes/+bug/1356978/comments/1) Fotis Tsamis - 2015-04-16 06:09:51 +0000

**Comment by alkisg** [comment]
That is doable, but tricky, as the state would have to be kept on the daemon, not on the various epoptes GUIs that might be running.
That means that the daemon wouldn't be just a transport anymore, it should be the one that defines the epoptes-client protocol commands.
That's a big change, not worth it for just this task.
Closing for now; it might be implemented in the future if other tasks require that big change.
