### ISSUE TITLE
Update VNC viewers support

### ISSUE THREAD

**Issue by alkisg** [epoptes/epoptes#140]
There were several changes in VNC viewers in the last years. For example xvnc4viewer is no longer available on Debian, even though we still provide it via the Greek Schools PPA.

We should update Epoptes in order to properly support as many of the following VNC viewers as possible:

* gvncviewer
* realvnc-vnc-viewer
* ssvnc
* tigervnc-viewer
* xtightvncviewer
* xvnc4viewer

We should make a list of the benefits and drawbacks for each one of them, for example availability, ability to scale etc.
Then we should update Epoptes so that it prefers them in the best order, and finally we should update the [respective documentation page](https://epoptes.org/documentation/vnc/).

**Comment by fottsia** [comment]
Broadcasting the teacher screen with RealVNC [doesn't work well](https://alkisg.mysch.gr/steki/index.php?topic=8838.msg95710#msg95710) before login.
It might be best not to use it as the default.

**Comment by alkisg** [comment]
Indeed, reverting to the previous recommendations.
