### ISSUE TITLE
Multi-monitor problem demo to clients. Show only one monitor.

### ISSUE THREAD

**Issue by Luckasas** [epoptes/epoptes#144]
If you have two monitors, the client views two monitors very, very small.
Is it possible to show only one monitor to clients? Maybe some file configuration or a option in the gui,...

**Comment by alkisg** [comment]
Thanks, I added `-clip xinerama0` only for screen broadcasting, not for screen monitoring, as that one is probably useful more frequently than not.

Builds will be available in the proposed PPA after a few hours.

**Comment by fottsia** [comment]
I tested the new build in a dual monitor setup, `-clip xinerama0` seems to work fine.
