### ISSUE TITLE
The client doesn't show to the server

### ISSUE THREAD

**Issue by anescdev** [epoptes/epoptes#147]
When i try to make the `sudo epoptes-client -c`, the client doesn´t connect to the server, the log show that: 
Can't use SSL_get_servername
depth=0 C = AU, ST = Some-State, O = Internet Widgits Pty Ltd
verify return:1
DONE
Successfully fetched certificate from 172.16.0.10:789

**Comment by alkisg** [comment]
@anescdev, to discuss things that relate to your setup, please open discussions: https://github.com/epoptes/epoptes/discussions

The https://github.com/epoptes/epoptes/issues are for bugs in the epoptes code, not for general help...
