### ISSUE TITLE
Support dnsmasq-hosts configuration files

### ISSUE THREAD

**Issue by ftsamis** [epoptes/epoptes#15]
1) We want to support global, read-only groups (labs).
2) We want to reuse existing configuration from other packages. It's easier for sysadmins to have the information in one place.

So the idea is to use dnsmasq's dhcp-hostsfile in order to implement global, readonly groups in epoptes.

man dnsmasq =>
--dhcp-host=[<hwaddr>][,id:<client_id>|*][,set:<tag>][,<ipaddr>][,<hostname>][,<lease_time>][,ignore]
--dhcp-hostsfile=<path>

A dhcp-hostsfile contains lines like these:
3c:07:71:a2:02:e3,set:lab1,,pc01
00:27:32:b3:2e:f2,set:lab1,,printer01,ignore
00:c0:9f:2a:ec:de,set:lab2,192.168.67.10,server02

We can get the mac addresses and the hostnames from there.
If a "set" tag is defined, the client should be put to that (new) group.
If there's no "set" tag, we should do the same as with currently do with the the [mac:address] entries of lts.conf, i.e. just get the client hostname in case it's declared in some user-defined group (btw maybe it would be better to put those in the autodetected computers group so that it's easier to WOL them out of the box).

The file could reside in /etc/epoptes/dnsmasq-dhcp-hosts, which may be a symlink to some other file if the sysadmin so prefers.

Launchpad Details: [#LP1469044](https://bugs.launchpad.net/bugs/1469044) Fotis Tsamis - 2015-06-26 07:32:02 +0000

**Comment by alkisg** [comment]
The dnsmasq hostnames don't work with proxyDHCP.
Aborting this idea in favor of HOSTNAMEs in ltsp.conf.
(btw global epoptes groups are already implemented)
Of course if someone does need this... patches welcome. :)
