### ISSUE TITLE
Crash with the epoptes server

### ISSUE THREAD

**Issue by anescdev** [epoptes/epoptes#151]
Hello Ñ, i have a problem with the epoptes server, when i try to start up, the console shot me that error. Some idea of how to fix it? Thank you in advance.

Traceback (most recent call last):
  File "/usr/bin/epoptes", line 15, in <module>
    import epoptes
ModuleNotFoundError: No module named 'epoptes'

**Comment by alkisg** [comment]
Hello @anescdev, which distribution / version / epoptes version is that?

**Comment by anescdev** [comment]
My distribution is ArchLinux, the latest version, epoptes, the 1.0

**Comment by alkisg** [comment]
The previous epoptes version was 21.02, the current one is 22.01.

For ArchLinux, you would need to contact the community to solve the issue; and then if it's something that can be applied upstream, I'd be happy to integrate it like I did for the last patch that the community mentioned:

https://aur.archlinux.org/pkgbase/epoptes-client/

Also feel free to start a github discussion, in case there are any other Arch Linux users here: 

https://github.com/epoptes/epoptes/discussions/
