### ISSUE TITLE
Allow GUI connections over TCP

### ISSUE THREAD

**Issue by maniaque** [epoptes/epoptes#161]
Historically we've been using epoptes for a couple of years for now, since the pandemic started. Our environment is built around virtual machines, so we've always had multiple teachers working with the same virtual class.

Epoptes is a perfect companion, but server, holding client desktop connections, was exposing an interface to GUI app with UNIX socket. It is good for a lot of reasons, for example, you can do authorization using groups.

But looking forward, this will block future development and movement to fully containerized environment: user or teacher is just a client of epoptes server, so it should be TCP, not local. These patches make it.

But there is more. When you would like to assist, you ask client to connect back to epoptes server, where teacher GUI resides. With TCP, it is not so easy, teacher have to give his address for a client to connect to.

Changes:
- introduces two new configuration parameters GUI_SERVER and GUI_PORT: epoptes server by default listens on all interfaces GUI_PORT, and epoptes GUI connects by default to GUI_SERVER listening on GUI_PORT. By default GUI_SERVER is localhost, no problem here.
- patches UI code to know the IP of the teacher, when initiating connection. Right now the best way to know "default" IP is to find out, where your gateway is. But there should be a configuration parameter, I think.
- patches client-functions to use not SERVER address to connect, but the address from the teacher
- removes some code, connected to checks of the epoptes group membership, GUI is communicating via TCP now
- and epoptes server now listens for GUI_PORT with plain TCP.

I've published code in my repo, by just cloning, here it is:
https://github.com/maniaque/epoptes/tree/container

@alkisg

**Comment by alkisg** [comment]
Hi @maniaque, thank you very much for this pull request,
unfortunately more things need to be resolved for a proper implementation, and personally I do not have time currently to do them.

Epoptes should be using a single port for all incoming connections. The current 789 port where the epoptes-client connections happen should be re-used for GUI connections as well, and if possible, it should also be used for tunneling VNC/socat traffic when the student and client are on different subnets; while if they are on the same subnet, the students can connect directly to the teacher.

Additionally, TCP authentication and authorization should be implemented, otherwise it's a huge security issue. Currently this is handled by Unix groups; it needs to be moved to the daemon part of GUI connections.

**Comment by maniaque** [comment]
I'm not so sure about single port. It has different goals, so I personally see no problem using another one. In Kubernetes or any other environment two ports means two separate Services, KISS as it is. And about subnet - we use Epoptes in different networks, no problem, as soon as you keep you routing nice.

Yes, about TCP auth - right now it could be done with firewall, and it's relatively easy, all Linux distros have it. Container-based environment means dedicated IP to each teacher, so no huge issue here. What do you think about shared secret, both to server and GUI client?

**Comment by maniaque** [comment]
Why four? We only need port 789 for epoptes server to talk to client, and we need port 790 for GUI to speak with server. All these ports were unassigned by IANA, AFAIK.

**Comment by alkisg** [comment]
The ports that epoptes needs are:

- Client connections
- GUI connections
- VNC connections (screen sharing)
- Socat connections (terminal sharing)

As VNC and socat connections are currently "per GUI connection", not "per daemon", it would make sense to consolidate all the four ports above into one multiplexed port. This will also allow for encrypted VNC and easier firewalling.

This doesn't need to happen as part of this PR. If you wish you can send a patch for e.g. GUI at port 790, and I'll do the multiplexing part much later when I get some free time.

**Comment by alkisg** [comment]
Another idea would be to use websockets (port 443) for TCP connections so that [noVNC](https://novnc.com/) could also be used.
That's a completely different approach and it would require many code changes; I'm only mentioning it for the distant future, not for now.

**Comment by maniaque** [comment]
We've been using noVNC for a long time, btw, but now moving forward to Guacamole, it has a lot of interesting auth capabilities.

**Comment by alkisg** [comment]
After implementing #182, I don't think this one is needed anymore.
Closing, please reopen if you can think of any use case where the SSH socket forwarding isn't suitable and this one is.
