### ISSUE TITLE
LAN benchmark broken in Ubuntu 22.04

### ISSUE THREAD

**Issue by fottsia** [epoptes/epoptes#164]
The LAN benchmark function doesn't work properly in Ubuntu 22.04.
Related discusion: https://sourceforge.net/p/iperf2/discussion/general/thread/aa6f0646ad/

**Comment by alkisg** [comment]
Thanks, fix committed, will upload to the PPA shortly, please test.

**Comment by fottsia** [comment]
Works for me, thanks, closing.
