### ISSUE TITLE
Reboot of more than 3 clients at once doesn't work correctly.

### ISSUE THREAD

**Issue by dluvdluv** [epoptes/epoptes#167]
Hello! I would like to ask the community/developer, about the strange behavior of epoptes.

I made lot of tests in our environment, and saw the only one case, the reboot raspberry command works as it must be (reboots flawlessly). Only 3 etherboot devices reboots normally.
When you try to reboot 5 or 10 devices at once, it doesn't guarantee their work. You can see 1/2/3 in non working state (only logoff). I tried to activate the debug log. But no joy till now ( nothing suspicious). May be it can be barcode connected scanners problem? (i think about to disable them and try again)
We have Rpi4 4gb model. 1gb ethernet in our environment. We have connected barcode scanners. The rpboot kernel is  RPBoot 4.19.0-17-amd64: , the etherboot raspberry ltsp kernel is: Linux 5.10.52-v7l+
epoptes server besides on the raspberry also, the kernel is: Linux rspb 5.10.103-v7l+
I also changed the parameters of : /etc/dnsmasq.d/ltsp-dnsmasq.conf    add dhcp-reply-delay=1/2//3
and the nfs /etc/default/nfs-kernel-server. RPCNFSDCOUNT=16 (from def 8 threads) 
But nothing helps. Because it happens at the state of reboot command, not boot itself.

Yes 4 shure, if the raspberry have the sdcard inside, you even doesn't feel the disconnections state. But without, it's not so.

Any thoughts?

**Comment by alkisg** [comment]
Hi @dluvdluv, try to run `reboot` without using epoptes at the same time to more than 3 clients. E.g. open a terminal, type `reboot` and try to press `<Enter>` at about the same time.
If it hangs again (as I imagine it will), then the problem isn't related to epoptes at all.

**Comment by dluvdluv** [comment]
Hi alksig! You are right. I used cluster ssh to execute the same command on multiple hosts at once. And the behavior is the same.
So that's say, it's not a epoptes problem. As i understand it can be some: system, rpi image, network tricks.
may be i'll try to make all that circle on the full x64 os image.
Thank You!
