### ISSUE TITLE
Sometimes get-display hangs

### ISSUE THREAD

**Issue by fottsia** [epoptes/epoptes#177]
Sometimes we see a logged out client in epoptes, we right click > Execute > Open terminal > Root, locally, and a few seconds later it completely disappears from epoptes.

Going to that client and running:

```shell
sudo -i
export $(/usr/share/epoptes-client/get-display)
```

...we see that this is what makes epoptes hang.

**Comment by alkisg** [comment]
I pinpointed this to the `xwininfo` call hanging; actually any xorg programs hang at that point.
I'm not sure what's causing it, maybe xorg is confused about the foreground console; it feels similar to the issue where VNC shows a black screen when you switch to vt2 by pressing Ctrl+Alt+F2.
I added a `timeout 1` in front as a workaround. I'm attaching a relevant strace below, in case we ever want to get to the bottom of this.

Please verify that the timeout works around the issue.

```
    xwininfo -root =>
    uname({sysname="Linux", nodename="ltsp123", ...}) = 0
    access("/var/lib/lightdm/.Xauthority", R_OK) = 0
    openat(AT_FDCWD, "/var/lib/lightdm/.Xauthority", O_RDONLY) = 4
    newfstatat(4, "", {st_mode=S_IFREG|0600, st_size=104, ...}, AT_EMPTY_PATH) = 0
    read(4, "\1\0\0\7s29pc03\0\0010\0\22MIT-MAGIC-COOKIE"..., 4096) = 104
    read(4, "", 4096)                       = 0
    close(4)                                = 0
    getsockname(3, {sa_family=AF_UNIX}, [124 => 2]) = 0
    fcntl(3, F_GETFL)                       = 0x2 (flags O_RDWR)
    fcntl(3, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
    fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
    poll([{fd=3, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=3, revents=POLLOUT}])
    writev(3, [{iov_base="l\0\v\0\0\0\22\0\20\0\0\0", iov_len=12}, {iov_base="", iov_len=0}, {iov_base="MIT-MAGIC-COOKIE-1", iov_len=18}, {iov_base="\0\0", iov_len=2}, {iov_base="\274#\203\235\331j\f\323\22\350W}\7\7\345j", iov_len=16}, {iov_base="", iov_len=0}], 6) = 48
    recvfrom(3, 0x5616fd9da700, 8, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
    poll([{fd=3, events=POLLIN}], 1, -1
    ^C
```

**Comment by fottsia** [comment]
Seems to work fine, thanks, closing the issue.
