### ISSUE TITLE
Optimize wait_for_dns

### ISSUE THREAD

**Issue by alkisg** [epoptes/epoptes#179]
The `epoptes-client > wait_for_dns` function tries to wait until DNS is up, to avoid wasting CPU in socat calls that are bound to fail.
It would be nice if epoptes could respond to netlink events, but it doesn't, so it has to resort to polling.

To minimize log spamming, the first delay is one minute, and it's increased by one more minute on each failure. This has two big drawbacks:

- If a client has been booted for a week without LAN connectivity, and then a connection to the epoptes SERVER is possible, the delay will be huge by then. There should be a cap.
- If MDNS is used (e.g. epoptes-server.local), and the epoptes SERVER is booted after the clients, it might take a few minutes to connect to it (see https://github.com/epoptes/epoptes/issues/162#issuecomment-1304878283).

It would be better to start with a delay of 5 seconds, increasing it by 1 second, with a cap of 60 seconds,
and to only log a single "will keep retrying" message.

**Comment by alkisg** [comment]
Fix committed, build uploaded in the proposed PPA, please test if it works as expected.

**Comment by fottsia** [comment]
Works for me, closing the issue.
