### ISSUE TITLE
Clients' local pointer movement can't be grabbed when they get assisted

### ISSUE THREAD

**Issue by ftsamis** [Epoptes/epoptes#18]
Due to a x11vnc limitation, only mouse buttons, not pointer movement, can be grabbed with -grabptr command line option. So, when Epoptes server assists a client with option grabkbdptr=True, client user can still move pointer locally, which can be annoying to the teacher.

Epoptes-client could circumvent this limitation by running a script that slows down (via xinput command) local pointer movement, waits for current x11vnc proccess to finish, and then restores local pointer movement.

Launchpad Details: [#LP1428141](https://bugs.launchpad.net/bugs/1428141) Laércio de Sousa - 2015-03-04 13:54:53 +0000

**Comment by alkisg** [comment]
This should probably be filed against x11vnc, not against Epoptes. Closing, please reopen if that's not the case.
