### ISSUE TITLE
Δυσλειτουργία epoptes σε υπολογιστή εργαστηρίου ubuntu 18.04

### ISSUE THREAD

**Issue by delisandreas** [epoptes/epoptes#185]
Αγαπητέ Άλκη, 
μετά τις διακοπές των Χριστουγέννων, ο υπολογιστής του εργαστηρίου με όνομα guest19 (00:c0:26:a5:87:91) (επισυναπτόμενο αρχείο) δυσλειτουργεί με το λογισμικό epoptes. Συγκεκριμένα, αν και κάνει boot από τον server (IP:10.33.33.82) μέσω του epoptes και λειτουργεί κανονικά στην συνέχεια τις εφαρμογές του, εν τούτοις, δεν επικοινωνεί καθόλου με το epoptes και δεν έχω καθόλου έλεγχο από τον server. Στον client δεν έγινε καμιά αλλαγή, μόνο οι αναβαθμίσεις του ubuntu 18.04, όπως και στους υπόλοιπους clients του εργαστηρίου. Τι θα πρέπει να γίνει για να λυθεί το πρόβλημα;

Με εκτίμηση
Ανδρέας Δελής
35ο Δημοτικό σχολείο Πατρών

![Στιγμιότυπο στο 2023-01-20 12-08-14](https://user-images.githubusercontent.com/123148944/213985229-939e2516-a4e5-4600-ba75-acf09a4f3be6.png)

**Comment by alkisg** [comment]
Καλημέρα Ανδρέα,

ο παρών χώρος είναι για αναφορά σφαλμάτων στον κώδικα του Επόπτη.
Αντίθετα, για βοήθεια στην επίλυση προβλημάτων, θα πρέπει να χρησιμοποιούνται οι μέθοδοι που αναφέρονται στην Ελληνική σελίδα υποστήριξης:
https://ts.sch.gr/wiki/linux/support/

Προτείνω να κοιτάξεις τη σελίδα αυτή για οδηγίες και να συνδεθείς στο Matrix ή στο IRC ώστε να δούμε το πρόβλημα ζωντανά με απομακρυσμένη βοήθεια.
Ενώ αν προτιμάς ασύγχρονη βοήθεια, ανέβασε το ίδιο ακριβώς μήνυμα στο Στέκι των Πληροφορικών και θα απαντήσω εκεί.

Καλή συνέχεια,
Άλκης
