### ISSUE TITLE
Copy File for Client (Request)

### ISSUE THREAD

**Issue by slipttees** [epoptes/epoptes#195]
add file transfer to client using ssh/scp

**Comment by alkisg** [comment]
Hi @slipttees, thanks for filing this issue but unfortunately [this answer](https://github.com/epoptes/epoptes/issues/13#issuecomment-441170319) is still valid.

If epoptes gets [support for custom actions](https://github.com/epoptes/epoptes/issues/86) then copying files could be implemented on top of that.
