### ISSUE TITLE
screen-lock can be bypassed

### ISSUE THREAD

**Issue by ftsamis** [Epoptes/epoptes#2]
when running a fullscreen program (eg tuxpaint) the user can bypass the screen lock just by clicking outside hiw window (tux paint runs in fullscreen -changes resolution to a lower one- and the screen lock shows the whole screen, but the lock is within the smaller window)

Launchpad Details: [#LP880774](https://bugs.launchpad.net/bugs/880774) Yannis Tsop - 2011-10-24 10:36:00 +0000

**Comment by ftsamis** [comment]
maybe running xrandr (and set resolution) before and after screen lock?

Launchpad Details: [#LPC](https://bugs.launchpad.net/epoptes/+bug/880774/comments/2) Yannis Tsop - 2011-10-24 13:41:52 +0000

**Comment by ftsamis** [comment]
I can't reproduce what you are describing with Epoptes on Ubuntu 10.04 (Gnome), even if I execute tuxpaint --fullscreen. 
Could you describe the exact steps you followed?

The truth is that when locking the screen we only block/grab the keyboard and leave the mouse.
But we should grab it too, as I just found out that you can indeed "bypass" (in another way than the one you describe) lock-screen: 

If you keep the mouse click pressed - *before* the admin locks your screen - on the title bar of a window e.g. terminal, then the lock-screen app doesn't grab the keyboard and the focus remains on the previous window. So if the window was a terminal, he could execute whatever command.
I think this would be solved, though, if we grab the mouse too, when locking the screen.

Launchpad Details: [#LPC](https://bugs.launchpad.net/epoptes/+bug/880774/comments/3) Fotis Tsamis - 2011-10-25 21:37:59 +0000

**Comment by ftsamis** [comment]
Hallo,

we use linux for vmware player and the linux starts vmware player in fullscreen too. If the vmware player has mouse and is fullscreen, the lock does not work.

We have updated the lock-screen script, it sends ctrl-alt-shift (vmware player shortcut to release mouse) to X server (using lineakd xsendkeys) and vmware player releases the mouse and then the lock screen works.


Regards,

Robert Wolf.

Launchpad Details: [#LPC](https://bugs.launchpad.net/epoptes/+bug/880774/comments/4) Robert Wolf - 2012-02-21 14:28:13 +0000

**Comment by ftsamis** [comment]
I am rewriting the lock-screen script to make it more effective.

Launchpad Details: [#LPC](https://bugs.launchpad.net/epoptes/+bug/880774/comments/5) Fotis Tsamis - 2015-12-18 14:23:01 +0000

**Comment by alkisg** [comment]
If this is still happenning with the newer Epoptes version, the reporter should please reopen this issue.
