### ISSUE TITLE
[Feature request] Allow to configure multiple servers in network

### ISSUE THREAD

**Issue by ftsamis** [Epoptes/epoptes#20]
At now we can configure only one server for clients in network. But very often organisations have multiple administrators that need access. 

Will be good to have ability for configure multiple servers for clients in network.

Launchpad Details: [#LP1580106](https://bugs.launchpad.net/bugs/1580106) Murz - 2016-05-10 09:33:14 +0000

**Comment by alkisg** [comment]
With the current Epoptes networking design, that would mean running one client instance for each controlling server.
And in some cases, things like two servers controlling the same client with x11vnc would become chaotic...

A workaround could be to set up an "epoptes daemon pc", and give remote access to that pc to all the administrators, using x2go or vnc.

Closing for now, maybe in some distant future Epoptes version.
