### ISSUE TITLE
Run command on client connection

### ISSUE THREAD

**Issue by eMPee584** [epoptes/epoptes#203]
Hi,
to non-persistently disable most of the games in classroom, we have implemented following prototype. The idea is that upon connection of a client, the server would issue a command `xdg-desktop-menu-transient hide [list of games]` to deactivate the games. So for that, we'd need a hook that fires upon establishing a connection. I looked at the epoptes code but not sure where and how to put it, so opening this issue :sweat_smile: ...
Also, to enable specific games near the end of the lesson, we would need a way to dispatch a command to all clients..

With this `/etc/X11/Xsession.d/90temp-menu-masking`:
```shell
# This allows disabling games in a non-persistent way for school usage

XDG_DATA_DIRS="/tmp/xdg-menu-mask:$XDG_DATA_DIRS"
export XDG_DATA_DIRS
```
and a `/usr/local/bin/xdg-desktop-menu-transient`:
```python
#!/bin/python3

"""
XDG menu mask prototype
"""
# pylint: disable=invalid-name,logging-fstring-interpolation

# Imports
import argparse
import logging
import os
from pathlib import Path
import xdg.DesktopEntry

logging.basicConfig(format='%(name)s:%(levelname)s %(message)s')
logger = logging.getLogger(Path(__file__).name)

# Define possible arguments
parser = argparse.ArgumentParser(description='Transient hiding of games and'
                                 'applications from xdg menus',
                                 epilog='( [!] implementation prototype )')
parser.add_argument('-v', '--verbose', help='Show what is being done.', action='store_true')
parser.add_argument('action', choices=['hide', 'unhide'], help='Action to invoke.')
parser.add_argument('menu_items', nargs='+', help='One or more menu items to operate on. '
                    'Specify the Basename of the menu file (with or without .desktop suffix).',
                    metavar='MENU_ITEM')

args = parser.parse_args()
hiding = args.action == 'hide'
if args.verbose:
    logger.setLevel(logging.INFO)
    logger.info('Arguments object: %s', args)

# Ensure transient menu path exists
xdg_menu_tmp_path = Path('/tmp/xdg-menu-mask', 'applications')
xdg_menu_tmp_path.mkdir(parents=True, exist_ok=True)

# Check whether xdg system is configured to recognize the transient directory
if not xdg_menu_tmp_path in os.getenv('XDG_DATA_DIRS').split(':'):
    logger.warning(f'The {xdg_menu_tmp_path} directory seems not to be included'
                    'in XDG_DATA_DIRS environment variable, masking will not work!')


# Iterate through menu items and invoke action
for menu_item in args.menu_items:
    mask_name = Path(menu_item).name.removesuffix('.desktop')
    mask_path = Path(xdg_menu_tmp_path, mask_name + '.desktop')
    mask_object = xdg.DesktopEntry.DesktopEntry(mask_path)

    if hiding:
        if not mask_object.getNoDisplay():
            mask_object.set('NoDisplay', 'true')
            mask_object.write()
            logger.info(f'created {mask_path} to hide {mask_name}')
        else:
            logger.info(f'{mask_name} already hidden')
    else: # unhiding
        if mask_object.getNoDisplay():
            mask_path.unlink()
            logger.info(f'removed {mask_path} to unhide {mask_name}')
        else:
            logger.info(f'{mask_name} already unhidden')

```

**Comment by alkisg** [comment]
Hi, possible hooks to execute actions are:

1. When a client boots
2. When system epoptes connects
3. When a user logs in
4. When session epoptes connects
5. When a teacher opens epoptes
6. When a teacher runs a command to the clients e.g. via the "execute command" dialog

Why do you want to do that on (3) instead of e.g. (1) and (6)?

**Comment by eMPee584** [comment]
Because the blacklist should be applied automatically and regardless of order server or client are booted in.

**Comment by alkisg** [comment]
That's exactly why it should be applied on (1) and not on (4).
E.g. suppose that an epoptes-client PC boots and works for a day. The blacklist won't be applied.
The next day the epoptes server boots. Then the blacklist is applied.

This is very inconsistent, it shouldn't be implemented that way, so I'll close this issue as "Won't fix".
Thank you for the idea though!

**Comment by eMPee584** [comment]
... the whole point of my use case is, that the blacklist shall only be applied temporarily, in school, during the lesson. Is that really "inconsistent" and not a valid usage scenario?

**Comment by alkisg** [comment]
It would make sense to implement it via epoptes if you wanted the teacher to send a command to blacklist when the lesson begins and one when the lesson ends. Teacher-initiated.

This is very different from "on client connection", i.e. hook (4) in the list above. I don't think implementing this in (4) is a good idea, whether it's temporary or not.
