### ISSUE TITLE
Security leak - Usb popup

### ISSUE THREAD

**Issue by negroscuro** [epoptes/epoptes#209]
Hello, I noticed while epoptes is being used to send teacher contents that if alumns insert a pen drive then Linux Mint in my case warns about new drive have been mounted then alumns can use ALT+TAB to change to a different window and do other things instead of follow teacher presentation.

**Comment by alkisg** [comment]
With Wayland I'm not sure that "lock screen" will be able to function at all.

So if anyone has a patch to offer, it'll be most welcome, but if not, I don't think anyone will work on this; quite possibly lock screen will be completely removed in the future...

**Comment by negroscuro** [comment]
Sorry if I explained myself wrongly. Students do that while teacher shows his screen, not when locking alumns.
So with this bug they change to web browser and play videogamess in class instead of follow the teacher presentation.
Thats why I am worried about it, its simle to put a pen drive and the do ALT+TAB.

**Comment by alkisg** [comment]
Switching away from the teacher's presentation certainly isn't a security leak so the title isn't appropriate,
but in any case the same rules apply, I won't think wayland will allow full screen windows to block all other windows and pop us. If anyone knows how to block them, patches welcome; although the patches would probably need to go to the vncviewer applications, not to epoptes which just runs them.

**Comment by negroscuro** [comment]
I see thank you and sorry for the inconvenience.
