### ISSUE TITLE
When multiple users logout simultanuasly connection to epoptes is lost

### ISSUE THREAD

**Issue by ftsamis** [Epoptes/epoptes#21]
When I select multiple (20+) users on fat clients and select logout sometimes (about 30% chances of happening), epoptes stops responding and after a while I get a message that connection to epoptes was lost. After a few more seconds epoptes closes/crushes. This usually happens when users work on LibreOffice and created LibreOffice files during their session.

Launchpad Details: [#LP1628378](https://bugs.launchpad.net/bugs/1628378) taxaza - 2016-09-28 05:49:17 +0000

**Comment by ftsamis** [comment]
I forgot to mention that I am using UBUNTU MATE 16.04 on the server.

Launchpad Details: [#LPC](https://bugs.launchpad.net/epoptes/+bug/1628378/comments/1) taxaza - 2016-09-28 05:53:19 +0000

**Comment by ftsamis** [comment]
I attach a screenshot of the problem.

Launchpad Details: [#LPC](https://bugs.launchpad.net/epoptes/+bug/1628378/comments/2) taxaza - 2016-09-28 10:24:28 +0000

**Comment by ftsamis** [comment]
Hello taxaza,

Could you please also attach your /var/log/epoptes.log so I can see exactly what's happening?



Launchpad Details: [#LPC](https://bugs.launchpad.net/epoptes/+bug/1628378/comments/3) Fotis Tsamis - 2016-09-30 20:26:44 +0000

**Comment by ftsamis** [comment]
I'll do it on Monday when I get back to the school server.



On 30/09/2016 11:26 μμ, Fotis Tsamis wrote:
> Hello taxaza,
>
> Could you please also attach your /var/log/epoptes.log so I can see
> exactly what's happening?
>



Launchpad Details: [#LPC](https://bugs.launchpad.net/epoptes/+bug/1628378/comments/4) taxaza - 2016-09-30 22:17:36 +0000

**Comment by ftsamis** [comment]
I attach all my logs.

Launchpad Details: [#LPC](https://bugs.launchpad.net/epoptes/+bug/1628378/comments/5) taxaza - 2016-10-03 09:32:35 +0000

**Comment by alkisg** [comment]
The older 0.5.10 Epoptes version is based on Python2/Gtk2 and will not receive any updates.

I uploaded the newer 1.0.0 version in the [Epoptes proposed PPA](http://www.epoptes.org/documentation/ppa) for Ubuntu 18.10, 18.04 and 16.04.
If you still have a the problem with that version, I could take a look.

**Comment by alkisg** [comment]
No reply in 2 months, closing this issue.
