### ISSUE TITLE
improve support for tigervnc

### ISSUE THREAD

**Issue by ftsamis** [epoptes/epoptes#22]
Debian is dropping support for xvnc4viewer (and xtightvnc) in the upcoming stretch release, and tigervnc-viewer appears to be *nearly* compatible with it as a replacement.

The attached patch gets this mostly working, but the xtigervncviewer processes don't response to the kill signal passed in stopTerminal (e.g. client -> broadcasts -> stop broadcasts). They also don't respond to manually killing the pid as root, even with "kill -9"...

the first monitor/assist work fine, but subsequent attempts require exiting the epoptes gui.

Broadcast windowed mode works, but broadcast fullscreen doesn't appear to work.

Using ssvnc might be an alternate option, but has a recommends on "default-jre | java5-runtime" packages, which pulls in quite a few packages, at least in Debian.

Launchpad Details: [#LP1655795](https://bugs.launchpad.net/bugs/1655795) Vagrant Cascadian - 2017-01-12 00:46:49 +0000

**Comment by ftsamis** [comment]
Thanks for reporting this Vagrant!

Maybe it is a good chance to have a look at gtk-vnc.

Launchpad Details: [#LPC](https://bugs.launchpad.net/epoptes/+bug/1655795/comments/2) Fotis Tsamis - 2017-01-15 19:46:50 +0000

**Comment by ftsamis** [comment]
I've noticed two separate issues, one is that `xtigervncviewer -listen` doesn't accept multiple incoming connections; I reported it in https://github.com/TigerVNC/tigervnc/issues/400.

The other one is that sometimes it doesn't exit cleanly, preventing new viewers from launching. Unfortunately I haven't found a reliable way to reproduce it, it only happens some times.

If upstream accepts those to be bugs, I guess we can recommend tigervnc in epoptes, and leave it up to the tigervnc debian maintainer to backport the fixes to debian stretch?

Launchpad Details: [#LPC](https://bugs.launchpad.net/epoptes/+bug/1655795/comments/3) Alkis Georgopoulos - 2017-01-18 07:04:10 +0000

**Comment by ftsamis** [comment]
I remembered that gtk-vnc doesn't have listen support, so it's a no go for now.

Main problem for now is the issue that Alkis opened on tigervnc upstream, but I don't think we'll get a fix soon enough there.

Opening multiple listening viewers (one per x11vnc connection) could be a solution, but I'd say we can just go with ssvncviewer which supports listening for multiple connections in one process.


Regarding "the first monitor/assist work fine, but subsequent attempts require exiting the epoptes gui.", this is mostly on our end and it's due to not waiting for the exit status of the vncviewer process in python, which makes it a zombie, and since xtigervncviewer -listen exits after the first connection is gone, we are left with a zombie process right after the first connection. Fix for that is trivial and will be pushed soon.

Launchpad Details: [#LPC](https://bugs.launchpad.net/epoptes/+bug/1655795/comments/4) Fotis Tsamis - 2017-01-18 13:26:48 +0000

**Comment by ftsamis** [comment]
@vagrantc We discussed with @alkisg about this issue and the plan for now is to support xvnc4viewer whenever it's present, which means we should depend on `xvnc4viewer < 4.1.1+X4.3.0+t-1` to make sure we exclude the transitional package in debian. If xvnc4viewer dependency is not met we should prefer ssvnc.

Finally support for tigervnc is there, but since it doesn't have multilisten capabilities we will only support assisting/monitoring one client at a time.

**Comment by vagrantc** [comment]
I'm thinking in Debian I'll want to drop the dependency on xvncviewer entirely at this point, but maybe we could have it build differently on Debian and Ubuntu?

It looks like there are a few patches in the upstream branch I should also pull in or make a new bugfix release...

**Comment by vagrantc** [comment]
looking at this again, tigervnc-viewer is the only one that "provides" vnc-viewer in Debian currently, so leaving vnc-viewer in the dependency chain will allow tighervnc-viewer to satisfy the dependency during upgrades...

**Comment by alkisg** [comment]
TigerVNC doesn't support multiple incoming connections.
It would be best to use a vnc library, not support tigervnc.

**Comment by alkisg** [comment]
Links to the features that tigervnc lacks:

* [xtigervncviewer -listen accepts only one connection](https://github.com/TigerVNC/tigervnc/issues/400)
* [scale remote screen to window](https://github.com/TigerVNC/tigervnc/issues/274)
* [Invisible cursor when used with x11vnc](https://github.com/TigerVNC/tigervnc/issues/1346)
