### ISSUE TITLE
openssl on VNC

### ISSUE THREAD

**Issue by srulikuk** [Epoptes/epoptes#25]
Can you please add OpenSSL for VNC connections?
Also after fetching certificate on the client do all connections use openssl or do i need to specify?

**Comment by alkisg** [comment]
Fix committed in https://github.com/Epoptes/epoptes/commit/d21bec22e0696df697e6d7d6f8b32a87ea816c4b.

Only terminal sharing via a secure connection was implemented. VNC-based secure screen sharing will have to be postponed until we implement a VNC client in epoptes, using one of the available libraries.
