### ISSUE TITLE
Alias not saved when clicking "ok"

### ISSUE THREAD

**Issue by trendzetter** [epoptes/epoptes#30]
I am not sure if this is a issue or just a difference in preference. 
I created groups and then added clients with aliases. My feeling was that the aliases were saved when I clicked "OK" but they were all gone when I rebooted the system. 
I now understand that the groups are saved on clean exit of epoptes gui. The clean exit is not always happening when rebooting. That is why it is probably better to save the group when there is a change that is explicitly confirmed (clicking "ok" to confirm a new alias) or even on implicit confirmation of a change (clicking the enter key to change the name of the group from "New group" to a custom name).

**Comment by alkisg** [comment]
Closed by GSoC 2023 Epoptes improvements #204.
Please test if the [proposed PPA build](https://epoptes.org/documentation/ppa/) resolves this issue.
