### ISSUE TITLE
client display is not scaled on remote control/view

### ISSUE THREAD

**Issue by ftsamis** [epoptes/epoptes#4]
The client display is not scaled to window of epoptes controller.

Launchpad Details: [#LP1006388](https://bugs.launchpad.net/bugs/1006388) Christoph Thielecke - 2012-05-30 13:04:16 +0000

**Comment by ftsamis** [comment]
Currently, we use xvnc4viewer for remote controlling/monitoring of the clients. You can bring up its menu by pressing F8 and select there the desired options.

We plan to replace xvnc4viewer with a custom dialog which will provide more options (Lock screen etc) in a toolbar, so I mark this as Triaged

Launchpad Details: [#LPC](https://bugs.launchpad.net/epoptes/+bug/1006388/comments/1) Fotis Tsamis - 2012-05-30 20:07:43 +0000

**Comment by ftsamis** [comment]
A.F.A.I.K., xvnc4viewer has no option for scaling, even in F8 menu.

In the other hand, ssvncviewer has a -scale option and a scaling item in F8 menu. Among all scaling possibilities, I like "fit" (auto-scaling according to viewer monitor's resolution) and "auto" (as "fit", but preserves aspect ratio from server).

Unfortunately, I failed to pass "-scale auto" in ssvncviewer command line for fullscreen broadcasts: this option seems to be ignored when ssvncviewer is launched. Nevertheless, I can access ssvncviewer's menu locally in clients and set scale to "auto".

Launchpad Details: [#LPC](https://bugs.launchpad.net/epoptes/+bug/1006388/comments/2) Laércio de Sousa - 2012-06-19 19:18:37 +0000

**Comment by ftsamis** [comment]
In fact, there's a bug in ssvnc preventing "-scale fit|auto" to work properly during invocation, as reported in http://sourceforge.net/tracker/index.php?func=detail&aid=3534150&group_id=243486&atid=1122545

Launchpad Details: [#LPC](https://bugs.launchpad.net/epoptes/+bug/1006388/comments/3) Laércio de Sousa - 2012-07-31 12:02:44 +0000

**Comment by alkisg** [comment]
Real VNC is properly supported nowadays, closing this issue.
