### ISSUE TITLE
Debian epoptes-client packaging: is the dependency on ifup still needed?

### ISSUE THREAD

**Issue by maxnet** [Epoptes/epoptes#42]
The current logic in which the system-wide instance of eptoptes-client is launched by a script in `/etc/network/if-up.d` does not work well on systems that do not let `ifup` manage their network interfaces.
E.g. Raspbian uses `dhcpcd` which does not seem to call the scripts in there.

Is there any reason the current approach is used?
And not e.g. a systemd unit depending on network-online?

**Comment by alkisg** [comment]
This is indeed the case; the Greek ministry of education stopped funding Epoptes development (for political, not technical reasons), so development now is only done for [sponsored](http://www.epoptes.org/documentation/bounties) feature requests/bugs.

**Comment by alkisg** [comment]
Fix committed in https://github.com/Epoptes/epoptes/pull/63.
Btw, the funding of Epoptes maintenance is OK for now.
