### ISSUE TITLE
get-display not working on systemd distributions

### ISSUE THREAD

**Issue by maxnet** [Epoptes/epoptes#43]
The get-display script currently only works properly on systems that use consolekit, while modern distributions use systemd-logind instead.

If a system-wide instance of epoptes-client is running on such systems, broadcasts fail to work due to this.
VNC viewer complains it is unable to open display (since get-display was unable to find DISPLAY and XAUTHORITY.)
If only a user instance of epoptes-client is running, they do work.

**Comment by alkisg** [comment]
Hi, I tried doing this with systemd/logind commands but I could not reliably get XAUTHORITY.
I didn't like having to use passwd and hardcoded lightdm paths.
So I ignored the attached patch and wrote https://github.com/Epoptes/epoptes/commit/445b2189596cd2aaa8fe36d18d3f9e3cdbbc4fab.
Could you test if it works for you, and reopen if not? Thanks!
