### ISSUE TITLE
Rewrite lock-screen script in python3 and Gtk3

### ISSUE THREAD

**Issue by ftsamis** [Epoptes/epoptes#45]
lock-screen is a script that is executed on the Epoptes clients and blanks the selected clients' screens. The script takes one argument which should be the message displayed to the user's screen.

This script is currently written in Python2 + pygtk and should be rewritten in Python3 + gtk3.

The script should effectively lock the user's screen, grab the keyboard and the mouse and hide the mouse pointer. The icon displayed and the fade-in animation of the text should remain the same.

**Comment by cshubhamrao** [comment]
Please have a look: [(gist) cshubhamrao/lock-screen3](https://gist.github.com/cshubhamrao/2a0403adca219a44cfb73fb251289ccf)

**Comment by ftsamis** [comment]
This seems to work! Please propose these changes with a pull request on the
master branch instead of a gist. After that I would suggest to focus on
your proposal for GSoC (please don't forget to include in your proposal the
PRs you've created).

As a bonus task please try to also hide the mouse pointer when the screen
is locked.

2018-03-15 10:34 GMT+02:00 Shubham Rao <notifications@github.com>:

**Comment by cshubhamrao** [comment]
Converting into PRs!

**Comment by alkisg** [comment]
Fix committed in https://github.com/Epoptes/epoptes/pull/63.
