### ISSUE TITLE
transition to python3

### ISSUE THREAD

**Issue by ftsamis** [Epoptes/epoptes#5]
The short of it is that python2 will be End-Of-Life in 2020, which, given Long-Term-Support release cycles, is not so far off, really...

https://lists.debian.org/debian-devel-announce/2015/04/msg00005.html

Launchpad Details: [#LP1495277](https://bugs.launchpad.net/bugs/1495277) Vagrant Cascadian - 2015-09-13 17:57:18 +0000

**Comment by ftsamis** [comment]
We really want to do that but the problem is that epoptes uses twisted, parts of which have not been ported to python3 yet (e.g. twisted.protocols.amp which we use). So, I guess that we'll have to wait until twisted, and specifically the parts of it that epoptes uses, officially supports python3.

https://twistedmatrix.com/trac/wiki/Plan/Python3#Details
https://twistedmatrix.com/trac/ticket/6833

Launchpad Details: [#LPC](https://bugs.launchpad.net/epoptes/+bug/1495277/comments/1) Fotis Tsamis - 2015-09-13 19:20:36 +0000

**Comment by alkisg** [comment]
That was done in GSoC 2018, closing.
