### ISSUE TITLE
Create a flatpak version of Epoptes on flathub

### ISSUE THREAD

**Issue by LeandroStanger** [Epoptes/epoptes#50]

**Comment by alkisg** [comment]
https://flatpak.org/faq/#Can_Flatpak_be_used_on_servers_too_
...mentions that flatpak isn't appropriate for server applications, such as epoptes-server.

I'm not a flatpak user, did I misunderstand anything?

**Comment by LeandroStanger** [comment]
A flatpak version for Endless OS

**Comment by alkisg** [comment]
According to people in the #flatpak IRC channel, server applications like epoptes-server can't really be packaged in flatpaks. Endless might be able to use containers like docker to ship such applications.
