### ISSUE TITLE
Epoptes (or python) ignores /etc/nsswitch.conf (winbind name provider)

### ISSUE THREAD

**Issue by albert-a** [Epoptes/epoptes#51]
We use multiple servers that access the same files.
We keep users account info and group membership in Samba AD for all servers
On all servers, we have lines in /etc/nsswitch.conf
passwd:         compat winbind
group:          compat winbind
For that reason the group 'epoptes' moved to AD.

On startup Epoptes checks wether current user belongs to group 'epoptes', but considers only local groups, not taking into account winbind groups. And because of that it failed to start.

This command comments out this check:

sed -ri '/^if not is_member/,/^$/s/^#?/#/' /usr/bin/epoptes

And epoptes starts without any issue.

Note, that in previous version, the check was implemented the other way (IMHO better) and was working in my setup. In previous version program was checking if the daemon socket is acessible.
Maybe you should rollback to the previous behaviour?

Best regards,
Albert

**Comment by alkisg** [comment]
I don't know of any Epoptes versions that have "if not is_member" checks.
Are you using a custom version?

See https://github.com/Epoptes/epoptes/blob/master/bin/epoptes.

**Comment by albert-a** [comment]
I'm sorry, it seems that I confused versions of epoptes.
The version with the problem is actually older.
The version with the problem is 0.5.7-1, and it is from standard ubuntu 14.04 repository.

On the other server we run epoptes that was installed from PPA repository (version 0.5.10-1~ubuntu14.04.1) and /usr/bin/epoptes is exactly the same as in the link you posted.

All I have to do is add epoptes PPA repository on my new server and update the system.

Thanks!

Best regards,
Albert
