### ISSUE TITLE
possibility to store the size and positions of client computers

### ISSUE THREAD

**Issue by ftsamis** [epoptes/epoptes#6]
It would be nice if the size and position of the clients can be saved. This is useful to place the clients in the way where they physically placed. Thats easier for teachers to find the right physically client.

Launchpad Details: [#LP1006374](https://bugs.launchpad.net/bugs/1006374) Christoph Thielecke - 2012-05-30 12:47:03 +0000

**Comment by alkisg** [comment]
Closing with "won't fix".
If someone needs this... patches welcome.
