### ISSUE TITLE
Root epoptes-client not starting in Ubuntu 18.04 thin clients

### ISSUE THREAD

**Issue by fottsia** [Epoptes/epoptes#60]
If I create a fat chroot in Ubuntu 18.04, root epoptes-client runs properly.
If I create a thin chroot, it doesn't start.
The session epoptes-client runs properly in both cases.

It sounds like something missing from the thin chroots?

**Comment by alkisg** [comment]
That's because the ifupdown package, which is used to launch epoptes-client, is missing there.

We'll need to implement a systemd unit to launch epoptes-client.

**Comment by alkisg** [comment]
Fix committed a couple of months ago.
