### ISSUE TITLE
Teachers can see themselves in Epoptes 18.06

### ISSUE THREAD

**Issue by fottsia** [Epoptes/epoptes#61]
In Epoptes 18.06, I can see an icon with my own session, so I can lock myself etc.
I think this wasn't happening in previous versions.

**Comment by alkisg** [comment]
Fix committed in https://github.com/Epoptes/epoptes/commit/67c703805077c1e12114153a56eb33272b6c3e9a.

**Comment by rweilert** [comment]
Thanks for deviating this thread, Alkis. Didn't read carefully.

Basically I don't mind seeing myself, as long as I stay invisible for others and the X-Hidden group continues to do its job.

**Comment by alkisg** [comment]
@rweilert, also check if this fixes it for you:

https://github.com/epoptes/epoptes/issues/123#issuecomment-710324172
