### ISSUE TITLE
Warnings when epoptes starts

### ISSUE THREAD

**Issue by fottsia** [Epoptes/epoptes#69]
When I start epoptes in Ubuntu 18.04, I see the following warnings:

> [Errno 2] No such file or directory: '/home/user/.config/epoptes/history'
> [Errno 2] Δεν υπάρχει τέτοιο αρχείο ή κατάλογος: '/home/user/.config/epoptes/groups.json'

**Comment by alkisg** [comment]
Fix committed in https://github.com/Epoptes/epoptes/commit/5f2de7ca9a7bc9133e6abfca94ef00caefc9267b.
