### ISSUE TITLE
add client presentation mode

### ISSUE THREAD

**Issue by ftsamis** [epoptes/epoptes#7]
It would be nice if a client can be used as presenter. This means that the client content of the client allowed by the teacher is shown on all other clients.

Launchpad Details: [#LP1006922](https://bugs.launchpad.net/bugs/1006922) Christoph Thielecke - 2012-05-31 13:57:01 +0000

**Comment by ftsamis** [comment]
You can do this even now.

Select the client and do "broadcasts > monitor user".

then select all the other clients and do "broadcasts > broadcast screen"

Launchpad Details: [#LPC](https://bugs.launchpad.net/epoptes/+bug/1006922/comments/1) Yannis Tsop - 2014-10-02 10:24:09 +0000

**Comment by alkisg** [comment]
The current UI suffices for presentation mode, closing this issue.
