### ISSUE TITLE
Some features of epoptes do not work in a Lubuntu 18.04 32bit client

### ISSUE THREAD

**Issue by giouli** [Epoptes/epoptes#73]
Preconditions

1. Epoptes server
2. Epoptes client (Lubuntu 18.04 32bit)

Steps to reproduce

1. Open epoptes server
2. Open Lubuntu epoptes client
3. Open epoptes application
4. Right click on the client
5. Select a) Broadcasts/Broadcast screen or b) Broadcasts/ Broadcast screen (windowed) or c) Execute/ Open terminal/ Root, remotely or d) Restrictions/ Mute sound

Expected result

The expected results should be:
5.a) Broadcast the administrator's screen to the client's screen on fullscreen
5.b) Broadcast the administrator's screen to the client's screen windowed
5.c) Open the selected terminal
5.d) Mute the sound on client's pc

Actual result

The actual results are:
5.a) Doesn't broadcast the administrator's screen to the client's screen on fullscreen, therefor it is not possible to tell if the Broadcasts/ Stop broadcasts selection is functional
5.b) Doesn't broadcast the administrator's screen to the client's screen windowed, therefor it is not possible to tell if the Broadcasts/ Stop broadcasts selection is functional
5.c) Doesn't open the selected terminal
5.d) Doesn't mute the sound on client's pc

**Comment by alkisg** [comment]
This is actually caused by two different issues,
1) debian/epoptes-client.if-up still being present now that we switched to systemd, and
2) epoptes-client/get-display not working in Lubuntu, see https://github.com/Epoptes/epoptes/issues/43

Both are now solved, thanks for the bug report.
