### ISSUE TITLE
Feature Request: Add a Survey Feature

### ISSUE THREAD

**Issue by lukasdragon** [Epoptes/epoptes#79]
Ability to send students a pop-up asking for input to a question. Answer may be multiple choice (A,B,C,D) or short answer with answer validation. Answer(s) should be entered by teacher before broadcasting survey. Students who answer with the correct response should have the teacher interface recognize answers in real time. Example: changing the colour of a student icon to represent a correct submitted answer.

**Comment by alkisg** [comment]
Hi, that's a great idea but I think it's outside of the current Epoptes development focus.
So I'm going to close it as "Won't fix", but if someone does want to implement it and send a patch for it, it'll be welcomed.

Btw of course it's possible to implement surveys with any other existing surveys tool and use the Epoptes execute feature to point the users to that URL or tool. It won't be exactly the same, but close enough.
