### ISSUE TITLE
Wish list: run multiline commands (quick scripts)

### ISSUE THREAD

**Issue by ftsamis** [epoptes/epoptes#9]
The "Execute command" feature in ITALC supports multiline commands, making it possible to write quick scripts to execute on clients. Currently in Epoptes, the same feature is only possible with one-liners, joining all lines with ";"s

I wonder it would be useful if Epoptes also supports multiline commands as well as current one-liners. Maybe it could save the quick script in history as a one-liner.

Launchpad Details: [#LP1050403](https://bugs.launchpad.net/bugs/1050403) Laércio de Sousa - 2012-09-13 12:29:51 +0000

**Comment by alkisg** [comment]
I think this can be closed in favor of #86, i.e. the user would store their multiline scripts in a directory, and epoptes would show them as custom actions.
