### ISSUE TITLE
If SERVER is an IP, epoptes-client fails with "Cannot resolve"

### ISSUE THREAD

**Issue by fottsia** [epoptes/epoptes#91]
If I set SERVER=192.168.1.10 in /etc/default/epoptes-client, then epoptes-client fails to connect with the following error message:

> Cannot resolve 192.168.1.10 while DNS appears to work, aborting.

It works fine though if I modify /etc/hosts instead.

**Comment by alkisg** [comment]
Fix committed in https://github.com/epoptes/epoptes/commit/0b39b0bd877338663b6e0f375949d4fc71a4fb35.
